import type { TrendDataPoint } from '../components/analytics/FocusTrend';
import type { WeeklyDataPoint } from '../components/analytics/WeeklyChart';
import type { BlockedApp } from '../components/blocked/BlockedAppCard';
import type { DailyGoal } from '../components/home/DailyGoalCard';
import type { Achievement } from '../components/profile/AchievementCard';

export const MOCK_GOALS: DailyGoal[] = [
  {
    id: '1',
    title: 'Deep Work Protocol',
    description: 'Complete a 90-min uninterrupted block',
    reward: '+50 FC',
    progress: 45,
    total: 90,
    unit: 'm',
    completed: false,
  },
  {
    id: '2',
    title: 'Dopamine Fast',
    description: 'Zero Instagram blocks triggered today',
    reward: '+20 FC',
    progress: 1,
    total: 1,
    unit: '',
    completed: true,
  },
  {
    id: '3',
    title: 'Consistency',
    description: 'Complete 4 standard Pomodoro cycles',
    reward: '+30 FC',
    progress: 1,
    total: 4,
    unit: 'c',
    completed: false,
  },
];

export const MOCK_WEEKLY_DATA: WeeklyDataPoint[] = [
  { day: 'Mon', hours: 2.5 },
  { day: 'Tue', hours: 3.8 },
  { day: 'Wed', hours: 1.5 },
  { day: 'Thu', hours: 4.2 },
  { day: 'Fri', hours: 5.0 },
  { day: 'Sat', hours: 6.5 },
  { day: 'Sun', hours: 4.8 },
];

export const MOCK_TREND_DATA: TrendDataPoint[] = [
  { label: '8am', value: 40 },
  { label: '10am', value: 75 },
  { label: '12pm', value: 85 },
  { label: '2pm', value: 45 },
  { label: '4pm', value: 90 },
  { label: '6pm', value: 95 },
  { label: '8pm', value: 60 },
];

export const MOCK_BLOCKED_APPS: BlockedApp[] = [
  {
    id: 1,
    name: 'Instagram',
    category: 'Social Media',
    blocked: true,
    icon: '📸',
    logo: 'https://img.icons8.com/fluency/96/instagram-new.png',
    packageName: 'com.instagram.android',
    bundleId: 'com.burbn.instagram',
  },
  {
    id: 2,
    name: 'YouTube',
    category: 'Video Streaming',
    blocked: true,
    icon: '▶️',
    logo: 'https://img.icons8.com/color/96/youtube-play.png',
    packageName: 'com.google.android.youtube',
    bundleId: 'com.google.ios.youtube',
  },
  {
    id: 3,
    name: 'Facebook',
    category: 'Social Media',
    blocked: true,
    icon: '👥',
    logo: 'https://img.icons8.com/fluency/96/facebook-new.png',
    packageName: 'com.facebook.katana',
    bundleId: 'com.facebook.Facebook',
  },
  {
    id: 4,
    name: 'WhatsApp',
    category: 'Messaging',
    blocked: false,
    icon: '💬',
    logo: 'https://img.icons8.com/color/96/whatsapp--v1.png',
    packageName: 'com.whatsapp',
    bundleId: 'net.whatsapp.WhatsApp',
  },
  {
    id: 5,
    name: 'Twitter',
    category: 'Social Media',
    blocked: true,
    icon: '🐦',
    logo: 'https://img.icons8.com/fluency/96/twitter.png',
    packageName: 'com.twitter.android',
    bundleId: 'com.atebits.Tweetie2',
  },
  {
    id: 6,
    name: 'TikTok',
    category: 'Short Video',
    blocked: true,
    icon: '🎵',
    logo: 'https://img.icons8.com/fluency/96/tiktok.png',
    packageName: 'com.zhiliaoapp.musically',
    bundleId: 'com.zhiliaoapp.musically',
  },
  {
    id: 7,
    name: 'Snapchat',
    category: 'Social Media',
    blocked: false,
    icon: '👻',
    logo: 'https://img.icons8.com/fluency/96/snapchat.png',
    packageName: 'com.snapchat.android',
    bundleId: 'com.toyopagroup.picaboo',
  },
  {
    id: 8,
    name: 'Reddit',
    category: 'Social Media',
    blocked: false,
    icon: '🤖',
    logo: 'https://img.icons8.com/color/96/reddit.png',
    packageName: 'com.reddit.frontpage',
    bundleId: 'com.reddit.Reddit',
  },
  {
    id: 9,
    name: 'Netflix',
    category: 'Entertainment',
    blocked: false,
    icon: '🎬',
    logo: 'https://img.icons8.com/color/96/netflix.png',
    packageName: 'com.netflix.mediaclient',
    bundleId: 'com.netflix.Netflix',
  },
  {
    id: 10,
    name: 'Telegram',
    category: 'Messaging',
    blocked: false,
    icon: '✈️',
    logo: 'https://img.icons8.com/color/96/telegram-app.png',
    packageName: 'org.telegram.messenger',
    bundleId: 'ph.telegra.Telegraph',
  },
  {
    id: 11,
    name: 'Discord',
    category: 'Communication',
    blocked: false,
    icon: '💬',
    logo: 'https://img.icons8.com/color/96/discord-logo.png',
    packageName: 'com.discord',
    bundleId: 'com.hammerandchisel.discord',
  },
  {
    id: 12,
    name: 'Spotify',
    category: 'Music',
    blocked: false,
    icon: '🎵',
    logo: 'https://img.icons8.com/color/96/spotify.png',
    packageName: 'com.spotify.music',
    bundleId: 'com.spotify.client',
  },
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: '1',
    title: 'First Blood',
    description: 'Complete your very first focus session',
    icon: '🎯',
    rarity: 'common',
    unlocked: true,
    unlockedAt: 'Jan 2026',
  },
  {
    id: '2',
    title: 'Iron Will',
    description: 'Maintain a 7-day focus streak',
    icon: '🔥',
    rarity: 'rare',
    unlocked: true,
    unlockedAt: 'Feb 2026',
  },
  {
    id: '3',
    title: 'Deep Diver',
    description: 'Complete a 3-hour uninterrupted session',
    icon: '🌊',
    rarity: 'epic',
    unlocked: false,
    progress: 68,
  },
  {
    id: '4',
    title: 'Ascendant',
    description: 'Reach Level 20 and earn 10,000 Focus Coins',
    icon: '⚡',
    rarity: 'legendary',
    unlocked: false,
    progress: 42,
  },
];
